name: containner
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
     image: node:17-alpine3.14
    steps:
      - name: Log node version
        run: node -v
      - name: Step with docker node version
        uses: docker://node:14-alpine3.14
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - name: Step with docker prrint message
        uses: docker://node:14-alpine3.14
        with:
          entrypoint: "/bin/echo"
          args: "Hello sravani"
